{% set name = "xyzpy" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xyzpy-{{ version }}.tar.gz
  sha256: baff50753fdcbd2112b901b544c14b9405f285bf5e1b117744f2db2bad10711b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - dask-core >=0.11.1
    - h5netcdf >=0.2.2
    - h5py >=2.6.0
    - joblib >=0.12
    - numpy >=1.10.0
    - pandas >=0.20
    - python >={{ python_min }}
    - tqdm >=4.7.6
    - xarray >=0.9.0
    - matplotlib-base >=2.2.0

test:
  imports:
    - xyzpy
    - xyzpy.gen
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://xyzpy.readthedocs.io
  summary: Easily generate large parameter space data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jcmgray
